---
title: "git_01"
author: "Leonel Bautista"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
In the velvet shroud of night so deep,  
Where secrets in constellations sleep,  
The stars ignite their cosmic dance,  
A silent waltz, a fleeting chance.  

Each twinkle holds a tale untold,  
Of ancient dreams and mysteries bold,  
Galaxies swirl in a cosmic rhyme,  
Echoing eons beyond our time.  

Moonlight weaves its silver strands,  
Upon the Earth in enchanted lands,  
Whispers of the stars, a lullaby,  
Guiding our dreams as they drift by.  

Night's canvas painted black and vast,  
Holds futures yet to be unmasked,  
As we gaze up with wonder wide,  
The universe invites us to confide.  

Ode to the night, to stars above,  
Igniting our hopes, igniting love,  
In the boundless sea of endless space,  
We find our wonder, our dwelling place.  